### PR TITLE
Upgrade Doctum to 5.4 and enable OpenSearch feature

### PR DESCRIPTION
**Pull request by williamdes**
Read the news: https://github.com/code-lts/doctum/releases/tag/v5.4.0
I added a bunch of features that support tags you probably use

Commits:
- Upgrade Doctum to 5.4 (a80d9081c975acbb8939593d6534563b03968a94)
- Enable support for base_url (30db2444d3e7483df9734bce6e07c210dc0e2d96) (This will enable [OpenSearch](https://developer.mozilla.org/en-US/docs/Web/OpenSearch) and allow you to start searching in documentation from your search bar!)

### CODE REVIEW

**Comment by andrewandante** [comment]
Nice, thanks @williamdes!

Looks good in theory, I'll give it a run through locally to sanity-check but it doesn't seem like there's too much to worry about there.

**Comment by andrewandante** [comment]
Looks good to me, thanks!

**Comment by williamdes** [comment]
> Looks good to me, thanks!

Thank you !
Maybe you can delete the branch `doctum` from this repo

**Comment by andrewandante** [comment]
Cleaned out a pile of old branches 😄

**Pull request merged**
