### PR TITLE
FIX Require Lookup directly to avoid needing PSR-4 autoloader

### PR DESCRIPTION
**Pull request by robbieaverill**

### CODE REVIEW

**Comment by dhensby** [comment]
I don't get why the autoloader wouldn't work on SSP :/

**Comment by andrewandante** [comment]
@robbieaverill any chance you could fill me in on what this change is for? Is there something we are missing on SSP that should be happening, or is this a case of API being a special snowflake?

**Comment by robbieaverill** [comment]
This was basically a hotfix because of a variety of reasons to do with using homer, I don't think it was SSP related at all. It was resolved in the end by dumping the composer autoloader manually using a command that disabled suhosin inline which was why composer wasn't working on the box. We can remove this if it's still there now :-)

**Comment by andrewandante** [comment]
Alright, no worries - just saw the comment and thought maybe there was a bug with SSP, but if not that's great :)

**Pull request merged**
